POST http://localhost:4000/register
Content-Type: application/json

{
"name":"degraft",
"email":"frimpsup2gmail.com",
"password":"silverdollor",
"isAdmin":"false"
}

###
GET http://localhost:4000/


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"frimpsup2gmail.com",
    "password":"silverdollor"
}

###
GET http://localhost:4000/products

######

POST http://localhost:4000/product
Content-Type: application/json

{
    "[isAdmin]":"true",
    "title":"don simon",
    "sku":"12344",
    "price":"35",
    "image":"",
    "description":"soft drink made from natural fruit",
    "category":"beverages",
    "quantity":"20"



}